### ISSUE TITLE
Only use before - do not load the full library

### ISSUE THREAD

**Issue by nicoesiea** [jpillora/xhook#101]
Hello,
I'm using this library to perform a before for all XHR requests (to inject specific a header) but it looks like a bazooka to kill a mosquito... Is it possible to only load a small piece of code (extracted from this lib for example) to perform only this kind of need?
Thank you,
Nico

**Comment by nicoesiea** [comment]
Is it possible to extract a piece of code, smaller than the full library but still working like the normal one??

**Comment by jpillora** [comment]
No sorry not possible
