### ISSUE TITLE
xhook wraps global fetch function without enable() being called

### ISSUE THREAD

**Issue by philcunliffe** [jpillora/xhook#109]
The presence of the enable() function implies to me that xhook wouldn't wrap the global window.fetch function until it's called which is not the case.

The wrap is caused by this line: https://github.com/jpillora/xhook/blob/gh-pages/dist/xhook.js#L602

It seems like the wrapping is intended to happen here: https://github.com/jpillora/xhook/blob/gh-pages/dist/xhook.js#L223

**Comment by mariuszste** [comment]
For those searching for this:

The readme clearly states that xhook is enabled by default.  
see: https://github.com/jpillora/xhook#xhookenable
