### ISSUE TITLE
Add Access Control Allow Origin Header

### ISSUE THREAD

**Issue by Dazzler1985** [jpillora/xhook#122]
Dear community

Hope someone can help me .
I have a resource that i need to use but it has no access control origin header.
Is it possible to add this header with xhook.
If so hope you can give me an example.

The function of url replace etc works like a charm. very happy with this.

**Comment by Kravimir** [comment]
I don't know if JHook can do this. What I would do is write a PHP script to scrape the file and cache it on my own site's server and then serve it with the desired headers.

**Comment by TrickyPi** [comment]
Xhook can't do this, you can add this header in server side.
