### ISSUE TITLE
Errors are passed to Promise.resolve instead of Promise.reject with xhook 1.4.9

### ISSUE THREAD

**Issue by kpcyrd** [jpillora/xhook#131]
I've noticed xhook hooks `fetch` in a way that introduces bugs around error handling.

## Without xhook

```html
<!DOCTYPE html>
<html>
    <body>

        <script>
            if( fetch.toString().indexOf('[native code]') > -1 ) {
                console.log("`fetch` doesn't appear to be hooked");
            } else {
                console.log("`fetch` appears to be hooked");
            }

            // this is supposed to fail
            fetch('http://127.0.0.1:8000/')
                .catch(err => {
                    console.log('network error:', err);
                    return Promise.reject(err);
                })
                .then(x => console.log('it worked:', x))
                .catch(err => console.log('any other error:', err));
        </script>

    </body>
</html>
```

![no-xhook-output](https://user-images.githubusercontent.com/7763184/174865846-c9fdf771-7c9b-4f84-b13d-1ba37c49762c.png)

We're expecting the request to fail, the browser is correctly running our code in `.catch`.

## With xhook

Same code but with xhook loaded:

```html
<!DOCTYPE html>
<html>
    <body>

        <!-- 1.4.9 -->
        <script src="xhook.min.js"></script>

        <script>
            if( fetch.toString().indexOf('[native code]') > -1 ) {
                console.log("`fetch` doesn't appear to be hooked");
            } else {
                console.log("`fetch` appears to be hooked");
            }

            // this is supposed to fail
            fetch('http://127.0.0.1:8000/')
                .catch(err => {
                    console.log('network error:', err);
                    return Promise.reject(err);
                })
                .then(x => console.log('it worked:', x))
                .catch(err => console.log('any other error:', err));
        </script>

    </body>
</html>
```

![with-xhook-output](https://user-images.githubusercontent.com/7763184/174866093-d4753c28-8778-4f76-b99e-b5fdceab5175.png)

The browser is logging `it worked` although it didn't and the argument it was passed is the error that was supposed to be passed to `.catch`.

**Comment by KVPasupuleti** [comment]
This is making me uncomfortable already :fearful:

@kpcyrd Is there any progress on this?

**Comment by KVPasupuleti** [comment]
Yeah, that should work. Btw, are there any alternatives for Xhook for intercepting XHR requests? 

I didn't find anything reliable in my research.

**Comment by jpillora** [comment]
Hey guys, see https://github.com/jpillora/xhook/issues/119 instead of fixing the coffeescript, I wanted to switch to this modern JavaScript port

it needs a bit of work on the tests, though shouldn’t be too hard to add your fixes to this branch

Let me know if you’re working on it, I’d like to merge it in and delete the old coffeescript

**Comment by jpillora** [comment]
also, just realised this is the `fetch` API (https://github.com/jpillora/xhook/commit/0259e67171ad790479b06a29fdc866744f0ee1a7) maybe the author @morsdyce might be able to help?

P.s. the coffeescript is finally dead, see `main` branch for the implementation going forward

**Comment by jpillora** [comment]
Once, #136 is working, we can push changes to the JS (not CS) source and fixes will be auto-released
