### ISSUE TITLE
Change the output of xhook in src/main.js

### ISSUE THREAD

**Issue by TrickyPi** [jpillora/xhook#152]
Currently, we cannot use xhook via `esm` or `cjs` format like so:

```js
import xhook from 'xhook';
xhook.before(()=>{
})
```

It will cause error in `webpack` or `vite`.

maybe we need to change the output of `src/main.js`, and generate `iife`, `cjs` and `esm` formats via build tools.

**Comment by jpillora** [comment]
Ahh yea sounds good
