### ISSUE TITLE
Aborted requests fails miserably in IE9

### ISSUE THREAD

**Issue by sondremare** [jpillora/xhook#27]
If a request is aborted (i.e timeout), IE9 will report this error: 'SCRIPT575: Could not complete the operation due to error c00c023f.'

This is a IE9 problem which basically crashes my entire app when xhook tries to access status and statusText from the XHR object. There should be a check if the request has been aborted/timed out, and prevent reding status and statusText in function readHead().

**Comment by mnaoumov** [comment]
This issue still occurs in **readBody** function
