### ISSUE TITLE
Calling .setRequestHeader before .open causes exception

### ISSUE THREAD

**Issue by brendanyounger** [jpillora/xhook#33]
Calling xhr.setRequestHeader('X-Blah', 'blah') before calling xhr.open() causes a type error since xhr.headerNames does not exist, so the code in setRequestHeader tries to dereference `undefined`.

**Comment by jpillora** [comment]
This is actually an invalid action:

```
var xhr = new XMLHttpRequest();
xhr.setRequestHeader("Foo", "Bar");

Uncaught DOMException: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': The object's state must be OPENED.
```
