### ISSUE TITLE
Feature: fetch() Support

### ISSUE THREAD

**Issue by ilyagelman** [jpillora/xhook#36]
Are there any plans for supporting the new fetch API?

**Comment by jpillora** [comment]
I would like to though it's quite a bit of work. I'll leave some resources here though for anyone wanting to give it a shot:

* https://developers.google.com/web/updates/2015/03/introduction-to-fetch?hl=en
* https://developer.mozilla.org/en/docs/Web/API/Fetch_API
* https://github.com/github/fetch
