### ISSUE TITLE
dynamic hack ajax

### ISSUE THREAD

**Issue by jasonzhuang** [jpillora/xhook#44]
It seems we should invoke `xhook.before` and `xhook.after` before any XMLHTTPRequest send. But the common scenario is we may do some before or after in another js. Like this way:

```
// run.js
var record = {send: function(data){console.log("send to server data: ", data);}};
xhook.after(function(request, response){
    record.send(response.text);
})
```

**Comment by jpillora** [comment]
Sorry, what was the question?

**Comment by jasonzhuang** [comment]
Sorry, it's my mistake. After including the xhook.js, it can invoke `xhook.before` and `xhook.after` anywhere and anytime.
