### ISSUE TITLE
Prevent certain requests from being intercepted

### ISSUE THREAD

**Issue by jasonhjohnson** [jpillora/xhook#45]
Hi,

Is there a way to prevent certain requests from being handled by xhook?

Thanks,
Jason

**Comment by jpillora** [comment]
There is not, best you can do is return early. Does xhook break something?

**Comment by jasonhjohnson** [comment]
How would I return early?

Thanks,
J

**Comment by jpillora** [comment]
See example https://github.com/jpillora/xhook/blob/gh-pages/example/ie-8-9-cors-polyfill.html#L39-L41
