### ISSUE TITLE
change response data later

### ISSUE THREAD

**Issue by jasonzhuang** [jpillora/xhook#48]
I want to change response data asynchronous, does it possible? something like following:
xhook.after(function(request, response){
    response.text = asyncData; // asyncData will return later from other place
})

**Comment by jpillora** [comment]
`xhook.after` handlers cannot be asynchronous, can you use `xhook.before` instead?

**Comment by jasonzhuang** [comment]
How? Or does it possible to make ajax call  later, so the asyncData can be received before `xhook.after`

**Comment by jasonzhuang** [comment]
How to use `xhook.before` asynchronous. Does it means in `xhook.before` we can wait for remote data and change response? Could you show a snippet code? thanks

**Comment by morsdyce** [comment]
hi @jasonzhuang 

`xhook.before` will hold your request until you call xhook callback, so you can do anything in the meantime and xhook will hold the request until you're ready to give it data by providing it to the callback.

Please see the examples at:
http://jpillora.com/xhook/

And specifically the fake response example:
http://jpillora.com/xhook/#fake-response
