### ISSUE TITLE
CDN link 404

### ISSUE THREAD

**Issue by perqa** [jpillora/xhook#56]
The CDN link in the ReadMe is broken:
`<script src="//cdn.rawgit.com/jpillora/xhook/1.3.1/dist/xhook.min.js"></script>`

Suggest to use this instead:
`https://cdnjs.cloudflare.com/ajax/libs/xhook/1.3.5/xhook.min.js`

**Comment by morsdyce** [comment]
Thanks, updated the link to use unpkg instead which takes the code directly from npm so we don't have to update it manually.

**Comment by jpillora** [comment]
Cool, unpkg is better, though it might be better to use `@1.4` rather than `@latest`

**Comment by morsdyce** [comment]
Yes, it would. I did just to avoid updating the readme on every release
