### ISSUE TITLE
Angular 1 support broken with 1.4.0

### ISSUE THREAD

**Issue by BaTbAbYDeV** [jpillora/xhook#57]
This commit 

https://github.com/jpillora/xhook/commit/6335390de851cd49382536c2500cb78c906b3147

breaks support for angular1 (the requests do not appear to be sent at all) .  Does anybody know how to fix this quickly without having to remove this commit from my branch (it would be nice to support both!!)

If I get a chance to debug it I will but I'm not using angular 2 at all at the moment.

Thanks!

**Comment by morsdyce** [comment]
I'll look into it, but will appericiate a failing example in case I can't reproduce.

**Comment by morsdyce** [comment]
I confirmed the bug and reverted the change for now until we understand what exactly is the issue.
For now if angular 2 needs this change you can use version 1.4.0 from npm.

Can you please specify why angular 2 needed this change and how I can test it?
I'd like to see what exactly is the issue when the facade is missing these properties.

**Comment by BaTbAbYDeV** [comment]
Thanks for confirming and updating - much appreciated!

@Abrissirba - do you have the insights into Angular 2 and the reasoning for these facade extensions? (Thanks!!)

**Comment by morsdyce** [comment]
Hi @Abrissirba,

I know it's been a while but I would love if you could provide more info about the fix you submitted that was mentioned here.
I tested Angular v2 & Angular v4 and was able to use xhook with them as intended so I could not understand why that fix was needed.
 
Let me know if you consider this to still be a problem with that change being reverted so we can try to understand what happens better.

Thanks!

**Comment by morsdyce** [comment]
Closing this as this issue has become stale, please let me know if this is still a concern.

Thanks
