### ISSUE TITLE
Check for a cached response in before hook

### ISSUE THREAD

**Issue by rtholmes** [jpillora/xhook#65]
I am trying to use a `before` hook to intercept a request, see if I have a response cached for that request, and if so return that body. If the request is not cached, I would like to have it 'pass through' to the network (and I would intercept the response with an `after` hook). Unfortunately, I cannot figure out how to pass the request through to the network in the `before` hook when when a `callback` param has been added. Is this possible? 

For example:
```
xhook.before(function (request, callback) {
        if (isCached(request.url)) {
            console.log('xhook - use cached value');
                callback({
                    status: 200,
                    text: 'cachedData',
                    headers: {
                        Foo: 'Bar'
                    }
                });
        } else {
            console.log('xhook - not cached; send to network');
        }
});
```

**Comment by morsdyce** [comment]
Hi @rtholmes 

If you call the callback with no parameters the request will pass through to the network.

**Comment by rtholmes** [comment]
@morsdyce Thanks so much for your help, works like a charm!
