### ISSUE TITLE
Implementation design

### ISSUE THREAD

**Issue by jiangts** [jpillora/xhook#68]
Hi,

I'm comparing xhook and [ajax-interceptor](https://github.com/slorber/ajax-interceptor/blob/master/index.js) and wondering why this library decided to provide a completely separate `facade` for the `XMLHttpRequest` implementation.

I may not have looked into it enough, but it looks like it's more work than simply overriding some functions on top of the original object.

I only ask because I believe the facade is doing something incorrectly. We've deployed a javascript SDK onto a customer's browser, and it's causing errors in the [following function from the papaparse library](https://github.com/mholt/PapaParse/blob/master/papaparse.js#L643).

Any help would be much appreciated!

**Comment by jiangts** [comment]
I submitted a patch for the particular issue I was facing in https://github.com/jpillora/xhook/pull/69, but am still curious re the design.

The patch is in #69

**Comment by jpillora** [comment]
Hi @jiangts by using a `facade` version of `XMLHttpRequest`, we can intercept everything and modify anything. A brief glance at `ajax-interceptor` tells me that it creates a global `readystatechange` event handler and not much else...

Thanks for the PR! Any and all fixes to non-adherence to the spec are greatly appreciated :)

**Comment by jiangts** [comment]
Right -- `ajax-interceptor` also seems to only override 1 method on the original `XMLHttpRequest` object at a time. Obviously, there are tradeoffs, but this seems like a wise approach in order to ensure the API to the "tainted" `XMLHttpRequest` object continues to be consistent.

I spent a couple hours debugging some weird code with `req.responseType = 'arraybuffer'` last night to no avail -- `xhook` was still returning the `response` as a string rather than arraybuffer type.

**Comment by jpillora** [comment]
That's strange, `responseType` should just be set on the underlying XHR object... It'd be great if you could make a simple HTML page demonstrating the issue and post a link to it on new issue. Closed with #69.
