### ISSUE TITLE
Storing XHR from Request Object

### ISSUE THREAD

**Issue by mainarke** [jpillora/xhook#70]
Hi,

From my understanding, the Request object is different from XMLHttpRequest(XHR) object. Is it possible to extract the XHR from the request object, store it locally, abort current request, and send this XHR later?

**Comment by jpillora** [comment]
What's the request object?

**Comment by mainarke** [comment]
Request object is the one used in  xhook.before(handler(**request**[, callback])[, index])

**Comment by mainarke** [comment]
The XHR object inside Request is request.xhr. But if I intercept it in the xhook.before() function, it does not contain necessary headers... (readystate=1)
