### ISSUE TITLE
getAllResponseHeaders does not include trailing CRLF

### ISSUE THREAD

**Issue by jsedlacek** [jpillora/xhook#72]
According to spec, the `getAllResponseHeaders` should include trailing CRLF:
https://xhr.spec.whatwg.org/#the-getallresponseheaders()-method

Xdomains implementation does not contain trailing CRLF.
https://github.com/jpillora/xhook/blob/gh-pages/src/xhook.coffee#L478

This breaks behavior of superagent, which pops the trailing CRLF:
https://github.com/visionmedia/superagent/blob/master/lib/client.js#L203

With xdomain trailing CRLF is not present, so the last header gets stripped.

**Comment by morsdyce** [comment]
Thanks for reporting this, could you mention how can I achieve the broken behaviour with superagent? this is quite surprising to me as I use superagent with xhook daily in all my projects and I haven't met this behaviour.

**Comment by jsedlacek** [comment]
Here is a repository that simulates the broken behavior.
https://github.com/jsedlacek/xdomain-repro

You can see that without xhook, the example works correctly:
https://github.com/jsedlacek/xdomain-repro/blob/master/client.js#L4

**Comment by morsdyce** [comment]
I've added the trailing CRLF and confirmed the assertion is now passing.
I'll add a test for this in the near future when I set up a local testing server for our e2e tests so we won't break this in the future.

Thanks for reporting this!

**Comment by morsdyce** [comment]
For some reason I don't see a reference to the commit that fixed it, the specific commit is: 28825775ad001c97a0527d97e1e555fe17171fd5 and the fix should be released in version 1.4.5

**Comment by jsedlacek** [comment]
Thanks for a quick fix!
