### ISSUE TITLE
XHookHttpRequest does not implement the XMLHttpRequest standard

### ISSUE THREAD

**Issue by hrobertson** [jpillora/xhook#74]
XHookHttpRequest does not implement the [XMLHttpRequest standard](https://xhr.spec.whatwg.org/).
The specific issue I encountered was that the responseText property is `undefined` until the resource is loaded, whereas the spec specifies that it should never be `undefined`.

This makes xhook incompatible with some 3rd party libraries.

More generally, if xhook is to function as a drop-in replacement for XMLHttpRequest, then it should adhere to the standard.

**Comment by morsdyce** [comment]
Hi @hrobertson!

Thanks for reporting this, we're trying our best to comply with the XMLHttpRequest standard although it is not trivial to figure out all the small details in the spec.

This is fixed in #75 and a new version should be released soon.

**Comment by hrobertson** [comment]
@morsdyce Thanks for that. I can see that fully implementing the spec will be an ongoing effort.

**Comment by morsdyce** [comment]
It is an ongoing effort, I use xhook daily as a dependency on another open source project which is run on multiple projects with various libraries for the past year and a half within my company and it seems quite stable so far (I actually test xhook releases this way before they're officially released).

I'm sure we'll find more use cases as time goes by, unfortunately going over the entire spec again and making sure everything is up to spec is a very time consuming task where that time could be spent better on writing more tests and future proofing this library.

Thanks again for reporting the issue!
