### ISSUE TITLE
how to modify the cookie in the request ?

### ISSUE THREAD

**Issue by WangLaoSeng** [jpillora/xhook#78]

**Comment by morsdyce** [comment]
If it's a client side cookie then you can modify it in the headers object. 
Please see modifying headers in the examples folder

**Comment by piratesephiroth** [comment]
> 
> 
> If it's a client side cookie then you can modify it in the headers object.
> Please see modifying headers in the examples folder

The example says "modify" but that it only adds new cookies.

**Comment by jpillora** [comment]
"Cookie" is a protected header - its always set by the browser. If its not
an HTTP-only cookie, you can update it with "document.cookie"
