### ISSUE TITLE
Both async and sync requests?

### ISSUE THREAD

**Issue by notgne2** [jpillora/xhook#80]
In the README it says: `You may use synchronous XHR, though this will cause asynchronous hooks to be skipped.`, is there any workaround for this or a way to resolve this in the library? I need this as I am proxying the requests of a browser library which fetches separate components using both sync and async requests.

**Comment by morsdyce** [comment]
I don't think it's possible right now as if an xhr is sync it does not fire async events.
In general sync requests are deprecated and are not recommended to be used in production.

For more info about this please see the following link:
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests
