### ISSUE TITLE
Error while using min version

### ISSUE THREAD

**Issue by bartholomews** [jpillora/xhook#84]
I'm getting this error while running a script with the v1.4.5 minified version:

`xhook.min.js:3 Uncaught ReferenceError: a is not defined
    at xhook.min.js:3
    at xhook.min.js:3`

If I just use the non-minified dist everything's fine.

**Comment by morsdyce** [comment]
Thanks for catching this, this was an attempt to get the minified version running on non web platforms, I guess I'll wait until I'll have time to move to rollup before attempting this again.

I'll rebuild and release a new version to fix it

**Comment by morsdyce** [comment]
Fixed in 1.4.6
